#!/bin/sh

set -e

# vars

case "$1" in
   configure)
	/usr/sbin/lliurex-update-mime || true
   ;;
   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
      echo "postinst called with unknown argument $1" >&2
      exit 1
   ;;
esac

#DEBHELPER#

exit 0
